import Head from "next/head";
import Image from "next/image";
import ScrollButton from "@/components/ScrollButton/ScrollButton";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <ScrollButton buttonText={"About"}/>
          <h1>test title</h1>
        </div>
      </main>
    </>
  );
}
